# Generated by Django 4.2.16 on 2024-09-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("cuisine", models.CharField(max_length=100)),
                ("rating", models.FloatField()),
                ("openHours", models.CharField(max_length=100)),
            ],
        ),
    ]
