# Generated by Django 4.2.16 on 2024-09-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restaurant_Search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
