# Generated by Django 4.2.16 on 2024-09-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Restaurant_Search", "0002_restaurant_latitude_restaurant_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="openHours",
            field=models.CharField(max_length=1000),
        ),
    ]
